
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yusufatakanözcan
 */
public class Cbox extends javax.swing.JFrame {
        String metin = "";
        int toplam = 0;
    /**
     * Creates new form Cbox
     */
    public Cbox() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gorsel = new javax.swing.JCheckBox();
        web = new javax.swing.JCheckBox();
        tarih = new javax.swing.JCheckBox();
        turkce = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btnTikla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gorsel.setText("Görsel - 3");

        web.setText("Web - 4");

        tarih.setText("Tarih - 2");

        turkce.setText("Türkçe - 2");

        jLabel1.setText("Ders - Kredi");

        btnTikla.setText("TIKLA");
        btnTikla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTiklaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTikla)
                    .addComponent(tarih)
                    .addComponent(web)
                    .addComponent(turkce)
                    .addComponent(gorsel)
                    .addComponent(jLabel1))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(gorsel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(web)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tarih)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(turkce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTikla)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTiklaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTiklaMouseClicked
        // TODO add your handling code here:
        String sonuc = "";
        if (gorsel.isSelected()){
            String []gelen = gorsel.getText().split("-");
            metin = metin + gelen[0].trim() + "\n";
            toplam = toplam + Integer.parseInt(gelen[1].trim());
            
            //metin = metin + "Görsel" + "\n";
           // toplam = toplam + 3;
        }
        
        if(web.isSelected()){
            String []gelen = web.getText().split("-");
            metin = metin + gelen[0].trim() + "\n";
            toplam = toplam + Integer.parseInt(gelen[1].trim());
            //metin = metin + "Web" + "\n";
            //toplam = toplam + 4;
        }
        
        if(tarih.isSelected()){
            String []gelen = tarih.getText().split("-");
            metin = metin + gelen[0].trim() + "\n";
            toplam = toplam + Integer.parseInt(gelen[1].trim());
            //metin = metin + "Tarih" + "\n";
            //toplam = toplam + 2;
        }
        
        if(turkce.isSelected()){
            String []gelen = turkce.getText().split("-");
            metin = metin + gelen[0].trim() + "\n";
            toplam = toplam + Integer.parseInt(gelen[1].trim());
            //metin = metin + "Türkçe" + "\n";
            //toplam = toplam + 2;
        }
        sonuc = metin + "\n" + "Toplam Kredi : " +String.valueOf(toplam);
        
       JOptionPane.showMessageDialog(this, sonuc);
       metin = "";
       toplam = 0;
        
       
        
    }//GEN-LAST:event_btnTiklaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cbox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTikla;
    private javax.swing.JCheckBox gorsel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox tarih;
    private javax.swing.JCheckBox turkce;
    private javax.swing.JCheckBox web;
    // End of variables declaration//GEN-END:variables
}
